### ISSUE TITLE
Add an example of sound in a program with a model program

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/papyrus#31]
We want to make sure we can introduce sounds via a Program and can modify sounds (e.g., gain, high pass filter)

**Comment by jbphet** [comment]
@BLFiedler - We now have a working demo that creates a model property and makes use of the tambo lib to play a sound and vary the pitch based on the model property's value.  Changing the volume would work pretty much exactly the same way.  Adding a filter is a bit trickier, because it's a less common use case that is not supported "out of the box" in tambo, but it can certainly be done.  So, I'm wondering if we should call this done or if having an example with a filter is particularly significant.

**Comment by BLFiedler** [comment]
Whatever works out of the box in tambo is good enough for me at this time! I was just tossing out possible sound modifications, but don't want to push work into changing phet libraries at this time if it's not for purely compatibility reasons!

Thanks all! Closing.
